services:
  web:
    build: .  # Cambia questo per puntare alla directory corrente
    command: python fashiondjango/manage.py runserver localhost:8000
    volumes:
      - web_app_data:/code  # volume per l'applicazione web
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # volume per il database
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
  web_app_data:  # definizione del volume per l'applicazione web
